title = "Notre-Dame de Paris"
baseURL =  "https://ayorindetayo.github.io/project_portfolio/"
languageCode = "en-us"
theme = "ananke"



DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true
canonifyURLs = true
[languages]
  [languages.en]
    title = "Ayorinde Project Portfolio"
    weight = 1
    contentDir = "content/en"
  
[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = "https://twitter.com/TayoOlanipekun"
  instagram = ""
  youtube = "https://www.youtube.com/channel/UCL7UuJjaCi55KRobmlGTTvg"
  github = "https://github.com/AyorindeTayo"
  gitlab = ""
  Medium = "https://olanipekunayo2012.medium.com/"

  linkedin = "https://www.linkedin.com/in/olanipekun-ayorinde-07624941/"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/image9.jpg"
  recent_posts_number = 2
